name: Build documentation on merge

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  build-documentation:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install flit
      run: pip install flit

    - name: Install yoke
      run: flit install --deps=all

    - name: Build documentation
      run: |
        sphinx-build -b html docs/ docs/_build/html

    - name: Upload documentation artifact
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/_build/html

  deploy-documentation:
    needs: build-documentation
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: documentation

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact-name: documentation